### ISSUE TITLE
Not able to select a browser from the Include or Exclude list. 

### ISSUE THREAD

**Issue by jpmedley** [mdittmer/web-apis#2]
* The default browser has the downward triangle indicating that I should be able select a browser, but no other browsers are available. 
* If I click the + to add a browser, the triangle does work, but the only available item is 'isTrusted'.

I'm seeing this in Firefox 48 as well as the Chrome version described below. 

Note that before opening this ticket I also did git pull npm install and npm run rebuild to make sure everything was fresh. I also determined that list json is being loaded.

Google Chrome	53.0.2785.116 (Official Build) (64-bit)
Revision	3f9c628bfd1de2c62de1ea41d0707d06cc760061-refs/branch-heads/2785@{#886}
OS	Mac OS X 
Blink	537.36 (@3f9c628bfd1de2c62de1ea41d0707d06cc760061)
JavaScript	V8 5.3.332.45
Flash	23.0.0.166
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by mdittmer** [comment]
This is an implementation detail of `<input list="foo">` and `<datalist id="foo">`. The way I tend to use this page is to start typing the name of the browser I want and use the resulting dropdown. (E.g., latest Edge using <E>, <up-arrow>, <enter>).

I'm going to mark this an "enhancement" and roll it into a UI refresh (if I ever get around to one for this experimental page). PRs for a UI refresh such as using Polymer components for this would be welcome :)

**Comment by mdittmer** [comment]
I think I misspoke in my statement before. I saw this as a genuine issue when my dependencies were out of sync. Try running `npm update` to fix the issue.

**Comment by jpmedley** [comment]
Ran npm update. Combo boxes now seem to be behaving properly. 

+1 to including list.json as enhancement.
