### ISSUE TITLE
get-own-property-names.js:4 Uncaught (in promise) TypeError: Cannot convert undefined or null to object(…)

### ISSUE THREAD

**Issue by jpmedley** [mdittmer/web-apis#3]
Occurs in getOwnPropertyNames() when I click Analyze. This is in the same version of Chrome as listed in my other ticket.

I'm filling separate tickets because I was unable to determine if these are related problems. 

Note that before opening these tickets I also did git pull npm install and npm run rebuild to make sure everything was fresh.

**Comment by mdittmer** [comment]
What are your inclusion and exclusion lists you create before clicking Analyze?

**Comment by jpmedley** [comment]
I'm getting this on the default values that appear in the include and exclude boxes.

**Comment by jpmedley** [comment]
This was also solved by running npm update.
