### ISSUE TITLE
Manual data collection broken

### ISSUE THREAD

**Issue by foolip** [mdittmer/web-apis#58]
Trying to follow https://github.com/mdittmer/web-apis#manual-data-collection-setup to collect data from Safari 11 and Technology Preview locally.

At commit 3136209e2825a13de4cb7d6373a9df0dd09ba1a5, the result was a 3-byte file (`{\n}`) called data/og/window____.json. At commit 2882e3a748f8d5d3188e3a37e9155a7a339cc645 there was a JavaScript error while collecting related to the environment. Rolling back to commit a1167c01a8a5c19b63df85778d695b2483a9cec5 it works again, so it's a problem introduced with the latest two commits on master.

**Comment by mdittmer** [comment]
This should be fixed by https://github.com/mdittmer/object-graph-js/commit/4e49dfe5a2dd9d0c0e91d6911177154253d19937

@foolip please verify.

**Comment by foolip** [comment]
Fixed by https://github.com/mdittmer/object-graph-js/commit/9de7609338b0afe8e47db4821a8ba6e9a1e22aee.
